name: Github actions
run-name: ${{ Github.actor}}
on: [push,pull_request]

jobs:
    Github-actions:
        runs-on: ubuntu-latest
        steps:
          - name: Hello World
            run: echo "running github actions"
jobs:
    Cheackout:
        runs-on: ubuntu-latest
        steps:
          - name: Cheackout code
            uses: actions/checkout@v2