name: CI/CD Pipeline - Docker

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERPASSWORD}}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERUSERNAME }}/demo-nodeapp-v1:latest .


    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/demo-nodeapp-v1:latest'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true


    - name: Push Docker image
      if: success()
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
