name: CI/CD Pipeline - Docker

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERPASSWORD}}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t demo-nodeapp-v1:latest .
    
    - name: List Docker images
      run: docker images


    - name: Push Docker image
      if: success()
      run: |
        docker tag demo-nodeapp-v1:latest ${{ secrets.DOCKERUSERNAME }}/demo-nodeapp-v1:latest
        docker push ${{ secrets.DOCKERUSERNAME }}/demo-nodeapp-v1:latest
